### PR TITLE
Update about.md to explain template-set docs and roles

### LINKED ISSUE #89: Update about.md file
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
We have new content for the about.md page at: https://docs.google.com/document/d/1pLuD0MJzx5wZDdXP3OaOyXyERXSR8uy7bLbkDt6-eGs/edit#
This reflects current thinking about what The Good Docs Project is about.

**Describe alternatives you've considered**
n/a

### PR DESCRIPTION
**Pull request by camerons**
## Purpose / why

Refined our about page to align with current thinking. Fixes #89 .

## What changes were made?

Update about.md to explain template-set docs and roles

## Verification

I've tested this renders properly on my local computer.

This update aligns with the Concepts page, reviewed by Alyssa at: https://docs.google.com/document/d/1pLuD0MJzx5wZDdXP3OaOyXyERXSR8uy7bLbkDt6-eGs/edit#

(I slightly tweaked for web presentation and removed links to other pages which are still in development.)

---

## Checklist

> __Pull-request reviewer__ should ensure the following

* [ ] Are issues linked correctly?
* [ ] Is this PR labeled correctly?
* [ ] If template updates: do they align with [developers.google.com/style/](https://developers.google.com/style/)?
* [ ] Did the PR receive at least one :+1: and no :-1: from core-maintainers?
* [ ] On merging, did you complete the merge using [keywords](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#manually-linking-a-pull-request-to-an-issue)?
* [ ] On merging, did you add any applicable notes to a [draft release](https://github.com/thegooddocsproject/templates/releases) and link to this PR?

### CODE REVIEW

**Comment by bwklein** [comment]
Looks good at https://deploy-preview-90--gdp-hugo.netlify.app/about/

I'll verify the markdown formatting soon. Looking for things like ventilated prose, etc.

**Comment by camerons** [comment]
As far as I'm aware, we haven't made any decisions re how we wrap our markdown text, such as using ventilated prose.
As such, I assume we should be accepting any formatting?

**Comment by bwklein** [comment]
> As far as I'm aware, we haven't made any decisions re how we wrap our markdown text, such as using ventilated prose.
> As such, I assume we should be accepting any formatting?

You are correct, I don't think there has been any official decision made. I'm not even sure at this point where that decision would be made officially or where it would be documented.  I will say that it is definitely my preference for content source files and I have been checking for it on every commit I've made and every PR I have reviewed for the website project.  So I will probably make suggestions in the file for you to accept.  If there is an official way to make a decision on how source files are formatted, then we should do that too.

**Comment by camerons** [comment]
>  If there is an official way to make a decision on how source files are formatted, then we should do that too.

The decision process we have recently adopted is to write a RFC and then get it approved. https://github.com/thegooddocsproject/request-for-comment

**Review by bwklein — APPROVED** [review]
Since it is my personal preference for this project to have each sentence on its own line, I made the changes to make approval and acceptance easy.  I will make an RFC to try to bring this forward as a general formatting requirement.

**Review by bwklein — APPROVED** [review]

**Pull request merged**
